stages:
  - parent

variables:
  GLOBAL_VARIABLE_FOO: "BAR" 

amd64:
  stage: parent
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  trigger:
    include: build-amd64.yml
    strategy: depend
    forward:
      pipeline_variables: true
  variables:
    STAGE_VARIABLE_FOO: "BAR"
    ARCH: "amd64"